apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod-test
 labels:
    app: web
    env: dev
spec:
    containers: 
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80 
